### ISSUE TITLE
Don't install node for others

### ISSUE THREAD

**Issue by fabiantheblind** [Coderwelsch/Spotify-Downloader-CLI#1]
Tell the users to install node. Give him some instructions. Don't install node for them. Publish your tool as clean node tool only.

**Comment by Coderwelsch** [comment]
Yes, for sure. But this is not simple as thought. In this case, i have to use a very special version of node (0.10.41) to install the node modules "spotify-web" and "proto-buf" which only could install (without as much warnings as possible) with this version of node. So i tried to pre-install it with the .41 version for more "usx". In the new rebrushed run.sh script i will fix that

**Comment by fabiantheblind** [comment]
Then tell the user to use [nvm](https://github.com/creationix/nvm) instead of silently installing him an older version of Node.js

**Comment by fabiantheblind** [comment]
Do as you think. I would prefer a good readme over somebody modifyling my system by running to install scripts of others. :-)

**Comment by Coderwelsch** [comment]
My mom wouldn't like this. Accessing the Terminal is Voodoo and devil's work for her. So i have to find a one click way for my 'target audience' :D In the 'rebrush' version I will try to prevent this evil workaround, bro 😊

**Comment by fabiantheblind** [comment]
ah. Okay. Its Momware. :laughing:

**Comment by Coderwelsch** [comment]
You name it 😅
